steps:
    # Build the container image
    - name: "gcr.io/cloud-builders/docker"
      args: ["build", "-t", "gcr.io/$PROJECT_ID/edusign-backend:$COMMIT_SHA", "."]
    # Push the container image to Container Registry
    - name: "gcr.io/cloud-builders/docker"
      args: ["push", "gcr.io/$PROJECT_ID/edusign-backend:$COMMIT_SHA"]
    # Deploy container image to Cloud Run
    - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
      timeout: 1200s
      entrypoint: gcloud
      args:
          - "run"
          - "deploy"
          - "edusign-backend"
          - "--image"
          - "gcr.io/$PROJECT_ID/edusign-backend:$COMMIT_SHA"
          - "--region"
          - "asia-southeast2"
images:
    - "gcr.io/$PROJECT_ID/edusign-backend:$COMMIT_SHA"
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
