CREATE DATABASE EDUSIGN;
USE EDUSIGN;

CREATE TABLE USERS (
    id int NOT NULL AUTO_INCREMENT,
    email varchar(255) NOT NULL,
    username varchar(255) NOT NULL,
    password varchar(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE TRANSLATION_HISTORIES (
    id int NOT NULL AUTO_INCREMENT,
    userid int NOT NULL,
    filelink varchar(255) NOT NULL,
    result text NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (userid) REFERENCES USERS(id) ON DELETE CASCADE
);

CREATE TABLE COURSES (
    id int NOT NULL AUTO_INCREMENT,
    coursename varchar(255) NOT NULL,
    filelink varchar(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE LETTER_DICTIONARY (
    id int NOT NULL AUTO_INCREMENT,
    letter varchar(255) NOT NULL,
    filelink varchar(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);